insert_statement ::=
                 <"INSERT"> <"INTO"> table_name
                 <"("> insert_cols <")">
                 <"VALUES">
                 <"("> insert_vals <")">

insert_cols ::= #"[_A-Za-z]\w*" [ { <","> #"[_A-Za-z]\w*" }+ ]

insert_vals ::=
                   ( character_string_literal
                   | exact_numeric_literal
                   | approximate_numeric_literal
                   | something_date_literal
                   | something_datetime_literal
                   | something_epochal_literal )
                   [ {
                     <",">
                     ( character_string_literal
                     | exact_numeric_literal
                     | approximate_numeric_literal
                     | something_date_literal
                     | something_datetime_literal
                     | something_epochal_literal )
                     }+ ]

table_name ::= #"[_A-Za-z]\w*"

approximate_numeric_literal ::=
             #"(\d+(\.(\d+)?)?|\.\d+)[eE](?:\+|-)?\d+"

character_string_literal ::= #"'[^']*'"

exact_numeric_literal ::= #"(\d+(\.(\d+)?)?|\.\d+)"

something_date_literal ::= <"date"> <"'"> #"\d{4}-\d{2}-\d{2}" <"'">

something_datetime_literal ::= <"datetime">
                           <"'">
                           #"\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}"
                           <"'">

something_epochal_literal ::= <"time"> <"'"> #"\d+" <"'">

